home:
    path:      /
    defaults:  { _controller: KEMuseumBundle:Main:index }

objet_search:
    path:      /objet/search/{id}
    defaults:  { _controller: KEMuseumBundle:Objet:view }
    requirements:
        id: \d+

objet_add:
    path:      /objet/add
    defaults:  { _controller: KEMuseumBundle:Objet:add }


objet_index_edit:
    path:      /objet/edit/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexEdit }

objet_edit:
    path:      /objet/edit/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:edit }


objet_index_delete:
    path:      /objet/delete/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexDelete }

objet_delete:
    path:      /objet/delete/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:delete }

etage_add:
    path:      /etage/add
    defaults:  { _controller: KEMuseumBundle:Etage:add }

etage_index_edit:
    path:      /etage/edit/index
    defaults:  { _controller: KEMuseumBundle:Etage:indexEdit }

etage_edit:
    path:      /etage/edit/{num_armoire_etage}
    defaults:  { _controller: KEMuseumBundle:Etage:edit }


etage_index_delete:
    path:      /etage/delete/index
    defaults:  { _controller: KEMuseumBundle:Etage:indexDelete }

etage_delete:
    path:      /etage/delete/{num_armoire_etage}
    defaults:  { _controller: KEMuseumBundle:Etage:delete }

etage_search:
    path:      /etage/search/{id}
    defaults:  { _controller: KEMuseumBundle:Etage:view }
    requirements:
        id: \d+