home:
    path:      /
    defaults:  { _controller: KEMuseumBundle:Main:index }

objet_search:
    path:      /objet/search/{id}
    defaults:  { _controller: KEMuseumBundle:Objet:view }
    requirements:
        id: \d+

objet_add:
    path:      /objet/add
    defaults:  { _controller: KEMuseumBundle:Objet:add }


objet_index_edit:
    path:      /objet/edit/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexEdit }

objet_edit:
    path:      /objet/edit/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:edit }


objet_index_delete:
    path:      /objet/delete/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexDelete }

objet_delete:
    path:      /objet/delete/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:delete }

objet_index_place:
    path:      /objet/place/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexPlace }

objet_place:
    path:      /objet/place/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:place }

etage_add:
    path:      /etage/add
    defaults:  { _controller: KEMuseumBundle:Etage:add }

etage_index_edit:
    path:      /etage/edit/index
    defaults:  { _controller: KEMuseumBundle:Etage:indexEdit }

etage_edit:
    path:      /etage/edit/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:edit }


etage_index_delete:
    path:      /etage/delete/index
    defaults:  { _controller: KEMuseumBundle:Etage:indexDelete }

etage_delete:
    path:      /etage/delete/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:delete }

etage_index_consult:
    path:      /etage/consult/index
    defaults:  { _controller: KEMuseumBundle:Etage:indexConsult }

etage_consult:
    path:      /etage/consult/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:consult }