home:
    path:      /
    defaults:  { _controller: KEMuseumBundle:Main:index }

home_action:
    path:      /accueil/{type}/{codeMessage}
    defaults:  { _controller: KEMuseumBundle:Main:index }

erreur:
    path:      /erreur/{type}/{code}
    defaults:  { _controller: KEMuseumBundle:Main:erreur }

objet_search:
    path:      /objet/search/{id}
    defaults:  { _controller: KEMuseumBundle:Objet:view }
    requirements:
        id: \d+

objet_add:
    path:      /objet/add
    defaults:  { _controller: KEMuseumBundle:Objet:add }

objet_edit:
    path:      /objet/edit/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:edit }

objet_delete:
    path:      /objet/delete/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:delete }

objet_index_place:
    path:      /objet/place/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexPlace }

objet_index_place_erreur:
    path:      /objet/place/index/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:indexPlace }

objet_place:
    path:      /objet/place/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:place }

objet_index_consult:
    path:      /objet/consult/index
    defaults:  { _controller: KEMuseumBundle:Objet:indexConsult }

objet_consult:
    path:      /objet/consult/{code}
    defaults:  { _controller: KEMuseumBundle:Objet:consult }

etage_add:
    path:      /etage/add
    defaults:  { _controller: KEMuseumBundle:Etage:add }

etage_add_erreur:
    path:      /etage/add/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:add }

etage_edit:
    path:      /etage/edit/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:edit }

etage_placement_objet:
    path:      /etage/placement_objet/{codeEtage}/{codeObjet}
    defaults:  { _controller: KEMuseumBundle:Etage:placementObjet }

etage_delete:
    path:      /etage/delete/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:delete }

etage_retirer_objet:
    path:      /etage/retirer_objet/{codeEtage}/{codeObjet}
    defaults:  { _controller: KEMuseumBundle:Etage:retirerObjet }

etage_index_consult:
    path:      /etage/consult/index
    defaults:  { _controller: KEMuseumBundle:Etage:indexConsult }

etage_index_consult_erreur:
    path:      /etage/consult/index/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:indexConsult }

etage_consult:
    path:      /etage/consult/{code}
    defaults:  { _controller: KEMuseumBundle:Etage:consult }

etage_ordre_up:
    path:      /etage/ordreUp/{idEtage}/{idObjet}
    defaults:  { _controller: KEMuseumBundle:Etage:ordreUp }

etage_ordre_down:
    path:      /etage/ordreDown/{idEtage}/{idObjet}
    defaults:  { _controller: KEMuseumBundle:Etage:ordreDown }

armoire_add:
    path:      /armoire/add
    defaults:  { _controller: KEMuseumBundle:Armoire:add }

armoire_edit:
    path:      /armoire/edit/{code}
    defaults:  { _controller: KEMuseumBundle:Armoire:edit }

armoire_delete:
    path:      /armoire/delete/{code}
    defaults:  { _controller: KEMuseumBundle:Armoire:delete }

armoire_index_consult:
    path:      /armoire/consult/index
    defaults:  { _controller: KEMuseumBundle:Armoire:indexConsult }

armoire_consult:
    path:      /armoire/consult/{code}
    defaults:  { _controller: KEMuseumBundle:Armoire:consult }

armoire_ordre_up:
    path:      /armoire/ordreUp/{idArmoire}/{idEtage}
    defaults:  { _controller: KEMuseumBundle:Armoire:ordreUp }

armoire_ordre_down:
    path:      /armoire/ordreDown/{idArmoire}/{idEtage}
    defaults:  { _controller: KEMuseumBundle:Armoire:ordreDown }
