<?php

namespace KE\MuseumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtageRepository extends EntityRepository
{

	public function getNbForArmoire($idArmoire) {
 
        return $this->createQueryBuilder('o')
                    ->select('COUNT(o)')
					->where('o.idArmoire = :idArmoire')
					->setParameter('idArmoire',$idArmoire)
					->getQuery()
                    ->getSingleScalarResult();
    }

}
